### ISSUE TITLE
Update to match actual version of original library

### ISSUE THREAD

**Issue by AlexByte** [mysticmind/mysticmind-htmlagilitypack#1]
Why it'not updated to v1.4.9.4 of original 2016-07-14?

**Comment by mysticmind** [comment]
If you read through the readme, I have added description "This fork points
to v1.4.9.4 of the actual source including namespaces".

I think it makes sense to match the version number of this library as in
the original, will take a look at it. It will reduce any surface area for
confusion.


On Apr 29, 2017 11:08 PM, "AlexByte" <notifications@github.com> wrote:

Why it'not updated to v1.4.9.4 of original 2016-07-14?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mysticmind/mysticmind-htmlagilitypack/issues/1>, or mute
the thread

**Comment by mysticmind** [comment]
Fixed, matched version published to Nuget along with the changes done to migrate the project to use new csproj.
